### ISSUE TITLE
May I add 2 json text in one message?

### ISSUE THREAD

**Issue by prozhong** [ELCHILEN0/AutoMessage#24]
If i write

'{text:"Click me to open Google!",clickEvent:{action:open_url,value:"http://google.com"},color:blue}'

its one blue “Click me to open Google!”

What if i want red "[server]" in front of? Meaning add another json text which color set red?
How can I add?

**Comment by ELCHILEN0** [comment]
["",{"text":"[Server]","color":"red"},{text:"Click me to open Google!",clickEvent:{action:open_url,value:"http://google.com"},color:blue}]

Take a look at http://minecraftjson.com if you want to see a Minecraft JSON editor.
